#ifndef FOCUS_CONFIG_H
#define FOCUS_CONFIG_H

#define FOCUS_CONFIG_NUMBER_OF_MOTORS 1
#define FOCUS_CONFIG_MOTOR_POLE_PAIRS 6
#define FOCUS_CONFIG_ENCODER_CPR      4096
#define FOCUS_CONFIG_SAMPLE_PERIOD    0.0001f

#define FOCUS_CONFIG_FOC_BANDWIDTH 50.f

#define FOCUS_CONFIG_CALIBRATE_CURRENT_VOLTAGE  3.f
#define FOCUS_CONFIG_CALIBRATE_CURRENT_VELOCITY 2.f
#define FOCUS_CONFIG_CALIBRATE_CURRENT_SAMPLES  1000

#define FOCUS_CONFIG_CALIBRATE_ENCODER_VOLTAGE               3.f
#define FOCUS_CONFIG_CALIBRATE_ENCODER_INDEX_VELOCITY        10.f
#define FOCUS_CONFIG_CALIBRATE_ENCODER_ZERO_TIME             0.5f
#define FOCUS_CONFIG_CALIBRATE_ENCODER_ECCENTRICITY_VELOCITY 2.f

#define FOCUS_CONFIG_CALIBRATE_MOTOR_SAMPLES              10000
#define FOCUS_CONFIG_CALIBRATE_MOTOR_RESISTANCE_VOLTAGE   2.f
#define FOCUS_CONFIG_CALIBRATE_MOTOR_INDUCTANCE_VOLTAGE   3.f
#define FOCUS_CONFIG_CALIBRATE_MOTOR_INDUCTANCE_FREQUENCY 600.f

#endif
