#ifndef FOCUS_CONFIG_H
#define FOCUS_CONFIG_H

#define FOCUS_CONFIG_MOTORS_NUM           1
#define FOCUS_CONFIG_SAMPLING_FREQUENCY   10000
#define FOCUS_CONFIG_FOC_BANDWIDTH        50.f
#define FOCUS_CONFIG_DEBUG_BUFFER_SAMPLES 200

#define FOCUS_CONFIG_MOTOR_POLE_PAIRS_NUM                   6
#define FOCUS_CONFIG_MOTOR_KV                               750
#define FOCUS_CONFIG_MOTOR_CALIBRATION_SAMPLES              10000
#define FOCUS_CONFIG_MOTOR_CALIBRATION_RESISTANCE_VOLTAGE   2.f
#define FOCUS_CONFIG_MOTOR_CALIBRATION_INDUCTANCE_VOLTAGE   3.f
#define FOCUS_CONFIG_MOTOR_CALIBRATION_INDUCTANCE_FREQUENCY 600.f

#define FOCUS_CONFIG_CURRENT_CALIBRATION_SAMPLES  1000
#define FOCUS_CONFIG_CURRENT_CALIBRATION_VELOCITY 2.f
#define FOCUS_CONFIG_CURRENT_CALIBRATION_VOLTAGE  2.f

// #define FOCUS_CONFIG_SENSORLESS_ENABLE
// #define FOCUS_CONFIG_SENSORLESS_VELOCITY_MINIMAL   50.f
// #define FOCUS_CONFIG_SENSORLESS_VELOCITY_BANDWIDTH 50.f
// #define FOCUS_CONFIG_SENSORLESS_ALIGN_TIME         0.25f
// #define FOCUS_CONFIG_SENSORLESS_ALIGN_VOLTAGE      3.f
// #define FOCUS_CONFIG_SENSORLESS_RAMP_TIME          1.f
// #define FOCUS_CONFIG_SENSORLESS_RAMP_VOLTAGE       2.f
// #define FOCUS_CONFIG_SENSORLESS_RAMP_LAMBDA        0.1f
// #define FOCUS_CONFIG_SENSORLESS_RAMP_VELOCITY      200.f
// #define FOCUS_CONFIG_SENSORLESS_SMO_G              0.5f
// #define FOCUS_CONFIG_SENSORLESS_SMO_M              1.f

#define FOCUS_CONFIG_ENCODER_ENABLE
// #define FOCUS_CONFIG_ENCODER_AB
#define FOCUS_CONFIG_ENCODER_ABI
// #define FOCUS_CONFIG_ENCODER_ABSOLUTE
#define FOCUS_CONFIG_ENCODER_CPR                               4096
#define FOCUS_CONFIG_ENCODER_VELOCITY_BANDWIDTH                50.f
#define FOCUS_CONFIG_ENCODER_CALIBRATION_ALIGN_TIME            0.5f
#define FOCUS_CONFIG_ENCODER_CALIBRATION_ALIGN_VOLTAGE         3.f
#define FOCUS_CONFIG_ENCODER_CALIBRATION_INDEX_SEARCH_VELOCITY 10.f
#define FOCUS_CONFIG_ENCODER_CALIBRATION_INDEX_SEARCH_VOLTAGE  3.f
#define FOCUS_CONFIG_ENCODER_CALIBRATION_ECCENTRICITY_VELOCITY 2.f
#define FOCUS_CONFIG_ENCODER_CALIBRATION_ECCENTRICITY_VOLTAGE  3.f
#define FOCUS_CONFIG_ENCODER_CALIBRATION_ECCENTRICITY_ENABLE

#endif
