#ifndef FOCUS_CONFIG_H
#define FOCUS_CONFIG_H

#define FOCUS_CONFIG_MOTOR_POLE_PAIRS            6
#define FOCUS_CONFIG_ENCODER_CPR                 4096
#define FOCUS_CONFIG_PANIC_DURATION              1
#define FOCUS_CONFIG_SAMPLE_PERIOD               0.00002f
#define FOCUS_CONFIG_CALIBRATE_ENCODER_VOLTAGE   4.f
#define FOCUS_CONFIG_CALIBRATE_ENCODER_ZERO_TIME 1.f
#define FOCUS_CONFIG_CALIBRATE_ENCODER_VELOCITY  5.f

#endif
