#ifndef FOCUS_CONFIG_H
#define FOCUS_CONFIG_H

#define FOCUS_CONFIG_MOTOR_POLE_PAIRS 7
#define FOCUS_CONFIG_ENCODER_CPR      4096
#define FOCUS_CONFIG_PANIC_DURATION   1
#define FOCUS_CONFIG_SAMPLE_PERIOD    0.00002f

#endif
